<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'tmdb.list_repository' shared service.

include_once $this->targetDirs[3].'/vendor/php-tmdb/api/lib/Tmdb/Repository/AbstractRepository.php';
include_once $this->targetDirs[3].'/vendor/php-tmdb/api/lib/Tmdb/Repository/ListRepository.php';

return $this->services['tmdb.list_repository'] = new \Tmdb\Repository\ListRepository(($this->services['tmdb.client'] ?? $this->getTmdb_ClientService()));
