<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQbBMsvX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQbBMsvX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQbBMsvX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQbBMsvX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQbBMsvX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QbBMsvX',
    'container.build_id' => '93b4f801',
    'container.build_time' => 1555002797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQbBMsvX');
