<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Mdxtew\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Mdxtew/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Mdxtew.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Mdxtew\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3Mdxtew\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3Mdxtew',
    'container.build_id' => '4b4e2d4e',
    'container.build_time' => 1554823215,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Mdxtew');
