<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxV7Zjt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxV7Zjt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGxV7Zjt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGxV7Zjt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGxV7Zjt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GxV7Zjt',
    'container.build_id' => '0235e1b0',
    'container.build_time' => 1554905148,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxV7Zjt');
