<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TUdjypM' shared service.

return $this->privates['.service_locator.TUdjypM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'request' => ['privates', '.errored..service_locator.TUdjypM.Tmdb\\HttpClient\\Request', NULL, 'Cannot autowire service ".service_locator.TUdjypM": it references class "Tmdb\\HttpClient\\Request" but no such service exists.'],
]);
