<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.TUdjypM.Tmdb\HttpClient\Request' shared service.

include_once $this->targetDirs[3].'/vendor/php-tmdb/api/lib/Tmdb/HttpClient/Request.php';

return $this->privates['.errored..service_locator.TUdjypM.Tmdb\HttpClient\Request'] = new \Tmdb\HttpClient\Request();
